import { Injectable, ForbiddenException, NotFoundException, InternalServerErrorException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiService {
  private genAI: GoogleGenerativeAI;
  // In-memory cache: key â†’ { data, expiresAt }
  private cache = new Map<string, { data: any; expiresAt: number }>();
  private readonly CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

  private getCached(key: string): any | null {
    const entry = this.cache.get(key);
    if (!entry) return null;
    if (Date.now() > entry.expiresAt) { this.cache.delete(key); return null; }
    return entry.data;
  }

  private setCache(key: string, data: any): void {
    this.cache.set(key, { data, expiresAt: Date.now() + this.CACHE_TTL_MS });
  }

  constructor(private readonly prisma: PrismaService, private configService: ConfigService) {
    this.genAI = new GoogleGenerativeAI(
      this.configService.get<string>('GEMINI_API_KEY') || 'dummy_key_for_build',
    );
  }

  private async getTripDetails(tripId: string, userId: string) {
    const trip = await this.prisma.trip.findUnique({
      where: { id: tripId },
      include: { members: true },
    });

    if (!trip) throw new NotFoundException('Trip not found');

    const isMember = trip.members.some((m) => m.userId === userId);
    if (!isMember) throw new ForbiddenException('Access denied');

    return trip;
  }

  async generateItinerary(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Plan an itinerary for a trip to ${trip.destination}.
      Start Date: ${trip.startDate.toDateString()}
      End Date: ${trip.endDate.toDateString()}
      Budget: ${trip.budget ? '$' + trip.budget : 'Flexible'}

      Return a JSON array of days. Each day should have a 'dayNumber' and an 'activities' array.
      Each activity should have 'title', 'description', 'locationName', and 'costEstimate'.
      Keep it realistic and concise. Output ONLY pure JSON.
    `;

    try {
      const model = this.genAI.getGenerativeModel({ 
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: 'application/json' }
      });

      const completion = await model.generateContent(prompt);
      const result = completion.response.text();
      
      if (!result) throw new InternalServerErrorException('No content generated by AI');

      // 1. Parse JSON
      const parsedData = JSON.parse(result);
      const days = parsedData.days || [];

      // 2. Clear old generated itinerary days for this trip, or create new ones
      // For simplicity here, we assume the frontend will process this response to either save it or review it.
      // We will just return it allowing the client to call POST /trips/:tripId/itinerary/day iteratively.

      // Alternatively, we could automatically inject it into the database:
      // (Implementation left for manual frontend confirmation for better UX).

      return {
        success: true,
        generatedItinerary: days,
      };
    } catch (error: any) {
      console.error('Gemini Error Details (Itinerary):', error);
      
      // Fallback for Demo/Recruiter Showcase if API key is exhausted
      if (error?.status === 429 || error?.message?.includes('429')) {
        console.warn('API Quota Exceeded. Returning realistic MOCK itinerary data.');
        return {
          success: true,
          generatedItinerary: [
            {
              day: 1,
              date: trip.startDate.toISOString().split('T')[0],
              activities: [
                { time: '10:00 AM', description: `Arrive in ${trip.destination} and check into your accommodation.`, costEstimate: 0 },
                { time: '01:00 PM', description: 'Enjoy a local welcome lunch near the city center.', costEstimate: 25 },
                { time: '03:30 PM', description: 'Take a casual walking tour to explore the main sights.', costEstimate: 0 },
                { time: '07:00 PM', description: 'Welcome dinner featuring regional specialties.', costEstimate: 40 }
              ]
            },
            {
              day: 2,
              date: trip.endDate.toISOString().split('T')[0],
              activities: [
                { time: '09:00 AM', description: 'Visit the most famous landmarks and historical sites.', costEstimate: 30 },
                { time: '01:30 PM', description: 'Grab street food or a quick bite for lunch.', costEstimate: 15 },
                { time: '04:00 PM', description: 'Relax at a local cafe or park and soak in the atmosphere.', costEstimate: 10 },
                { time: '08:00 PM', description: 'Farewell dinner and packing up for departure.', costEstimate: 50 }
              ]
            }
          ]
        };
      }
      
      throw new InternalServerErrorException('Failed to generate itinerary. Please try again.');
    }
  }

  async generatePackingList(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Create a comprehensive packing list for a trip to ${trip.destination} between ${trip.startDate.toDateString()} and ${trip.endDate.toDateString()}.
      Output ONLY a JSON object with categories as keys (e.g. "clothing", "electronics") and arrays of strings as values.
    `;

    try {
      const model = this.genAI.getGenerativeModel({ 
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: 'application/json' }
      });
      
      const completion = await model.generateContent(prompt);
      return JSON.parse(completion.response.text() || '{}');
    } catch (error: any) {
      console.error('Gemini Error Details (Packing):', error);
      
      // Fallback for Demo/Recruiter Showcase if API key is exhausted
      if (error?.status === 429 || error?.message?.includes('429')) {
        console.warn('API Quota Exceeded. Returning realistic MOCK packing list.');
        return {
          "Clothing": ["T-shirts/Tops", "Comfortable walking shoes", "Jacket/Sweater for evenings", "Underwear and socks"],
          "Toiletries": ["Toothbrush and toothpaste", "Deodorant", "Sunscreen", "Travel-sized shampoo/body wash"],
          "Electronics": ["Smartphone and charger", "Power bank", "Universal travel adapter", "Headphones"],
          "Documents": ["Passport/ID", "Travel insurance details", "Booking confirmations", "Emergency cash"]
        };
      }

      throw new InternalServerErrorException('Failed to generate packing list.');
    }
  }

  async generateTravelTips(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Provide 5 crucial travel tips, cultural norms, and safety warnings for visiting ${trip.destination}.
      Output ONLY a JSON array of strings.
    `;

    try {
      const model = this.genAI.getGenerativeModel({ 
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: 'application/json' }
      });
      
      const completion = await model.generateContent(prompt);
      const result = completion.response.text();
      return { tips: result };
    } catch (error: any) {
      console.error('Gemini Error Details (Tips):', error);
      
      // Fallback for Demo/Recruiter Showcase if API key is exhausted
      if (error?.status === 429 || error?.message?.includes('429')) {
        console.warn('API Quota Exceeded. Returning realistic MOCK travel tips.');
        return { 
          tips: JSON.stringify([
            `Always carry around $50-$100 in local cash for small vendors in ${trip.destination}.`,
            "Learn a few basic phrases in the local language; locals appreciate the effort.",
            "Download offline maps on your phone in case you lose cell service.",
            "Keep emergency contact numbers and hotel addresses written on a physical card.",
            "Be mindful of local cultural dress codes, especially when visiting religious sites."
          ])
        };
      }

      throw new InternalServerErrorException('Failed to generate travel tips.');
    }
  }

  async generateDestinationOverview(destination: string) {
    const cacheKey = `overview:${destination.toLowerCase().trim()}`;
    const cached = this.getCached(cacheKey);
    if (cached) { console.log(`[AI Cache HIT] overview for ${destination}`); return cached; }

    const prompt = `
      Act as an expert travel guide. Provide a detailed, highly accurate, and engaging travel overview of "${destination}" as a JSON object with these keys:
      "description" (A comprehensive 3-4 paragraph overview of the destination's vibe, culture, and what makes it special),
      "history" (A detailed 2-3 paragraph summary of its historical significance and major eras),
      "topAttractions" (An array of 5 top must-visit tourist attractions with a brief 1-sentence description for each),
      "weather" (Detailed typical climate/temperature throughout the year),
      "bestTimeToVisit" (The best months to visit and why),
      "language" (Primary and secondary languages spoken),
      "currency" (Local currency name and symbol),
      "timezone" (Standard timezone info relative to GMT/UTC),
      "transport" (Detailed common transport options and best ways to get around locally).
      
      Ensure the information is factually correct and up-to-date. Output ONLY pure JSON.
    `;

    try {
      const model = this.genAI.getGenerativeModel({ 
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: 'application/json' }
      });
      
      const completion = await model.generateContent(prompt);
      const parsed = JSON.parse(completion.response.text() || '{}');
      this.setCache(cacheKey, parsed);
      return parsed;
    } catch (error: any) {
      console.error('Gemini Error (Overview):', error);
      
      // Fallback mock data
      return {
        description: `${destination} is a vibrant travel destination celebrated for its unique culture, stunning landscapes, and rich heritage. Its buzzing streets, flavorful cuisine, and welcoming locals make it a remarkable experience for every traveller. Whether you are here for history, nature, or just soaking in the atmosphere, ${destination} has something unforgettable for everyone.`,
        history: `${destination} has a fascinating history spanning centuries, shaped by ancient civilizations, trade empires, and colonial influences that have left an indelible mark on its architecture, culture, and traditions. The city has witnessed the rise and fall of kingdoms and has emerged as a modern metropolis while still honouring its storied past.`,
        topAttractions: [
          `Historic Old Town â€” Wander through ancient bazaars and heritage monuments that tell the story of ${destination}'s past`,
          "Natural Landmarks â€” From cascading waterfalls to scenic viewpoints, the surrounding nature is breathtaking",
          "Local Museums â€” Curated collections showcasing the art, artefacts, and stories of the region",
          "Street Food Trail â€” Sample iconic local flavours from the night markets and street stalls",
          "Sacred Temples & Monuments â€” Majestic religious and historical sites that define the city's skyline"
        ],
        bestTimeToVisit: "October to March is generally the most comfortable window to visit, with moderate temperatures and clear skies. Festivals during this period make it even more vibrant.",
        weather: "Tropical climate with hot summers (35-40Â°C), a monsoon season (June-September), and pleasant winters (15-25Â°C)",
        language: "Hindi, English, and local regional languages",
        currency: "INR (â‚¹) â€” Indian Rupee",
        timezone: "UTC+05:30 (India Standard Time)",
        transport: "Auto Rickshaws, City Buses, Taxis/Cabs (Ola/Uber), Metro Rail (in larger cities), and local trains",
      };
    }
  }

  async generateDestinationHighlights(destination: string) {
    const cacheKey = `highlights:${destination.toLowerCase().trim()}`;
    const cached = this.getCached(cacheKey);
    if (cached) { console.log(`[AI Cache HIT] highlights for ${destination}`); return cached; }

    const prompt = `
      Act as a travel expert. For the destination "${destination}", provide a JSON object with:
      "attractions": array of 6 top tourist places to visit (each: { "name": string, "description": string (1 sentence) }),
      "thingsToDo": array of 6 top activities/experiences (each: { "name": string, "description": string (1 sentence) }),
      "foods": array of 6 must-try local dishes or food experiences (each: { "name": string, "description": string (1 sentence) }),
      "culture": array of 4 cultural highlights or festivals (each: { "name": string, "description": string (1 sentence) }).
      Make it specific and factually accurate for ${destination}. Output ONLY valid JSON.
    `;

    try {
      const model = this.genAI.getGenerativeModel({
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: 'application/json' },
      });
      const completion = await model.generateContent(prompt);
      const result = JSON.parse(completion.response.text() || '{}');
      this.setCache(cacheKey, result);
      return result;
    } catch (error: any) {
      console.error('Gemini Error (Highlights):', error);
      return {
        attractions: [
          { name: 'Old Town Quarter', description: `The historic heart of ${destination} with ancient architecture and vibrant bazaars.` },
          { name: 'Central Park & Gardens', description: 'A serene green escape with beautiful landscaping and scenic walks.' },
          { name: 'Art & History Museum', description: 'Curated collections tracing the rich cultural journey of the region.' },
          { name: 'Waterfront Promenade', description: 'A stunning walkway along the water with views, cafes, and street performers.' },
          { name: 'Royal Palace / Fort', description: 'An iconic royal landmark offering panoramic views and fascinating history.' },
          { name: 'Local Night Market', description: 'A bustling evening market with street food, crafts, and local culture.' },
        ],
        thingsToDo: [
          { name: 'Street Food Tour', description: 'Explore local flavours on a guided or self-guided street food adventure.' },
          { name: 'Sunrise Viewpoint', description: 'Catch breathtaking dawn views from the city most iconic high point.' },
          { name: 'Local Cooking Class', description: 'Learn to cook traditional dishes with expert local chefs.' },
          { name: 'Cycling Tour', description: 'Pedal through neighbourhoods and discover hidden gems off the tourist trail.' },
          { name: 'Temple / Religious Site Visit', description: 'Experience the spiritual ambiance of the most revered places of worship.' },
          { name: 'Day Trip to Countryside', description: 'Escape the city for scenic rural villages, waterfalls, or nature reserves.' },
        ],
        foods: [
          { name: 'Local Biryani', description: 'Aromatic spiced rice with slow-cooked meat, a regional staple.' },
          { name: 'Street Chaat', description: 'Crispy, tangy, and spicy street snacks bursting with flavour.' },
          { name: 'Masala Dosa', description: 'Crispy crepe filled with spiced potatoes, served with chutneys.' },
          { name: 'Filter Coffee', description: 'Strong, aromatic coffee brewed the traditional way.' },
          { name: 'Seafood Platter', description: 'Fresh catch-of-the-day prepared with regional spices and coconut.' },
          { name: 'Local Sweets', description: 'Traditional confections crafted with jaggery, coconut, and cardamom.' },
        ],
        culture: [
          { name: 'Classical Dance Performances', description: 'Live performances of regional classical dance forms at local theatres.' },
          { name: 'Temple Festivals', description: 'Vibrant religious festivals with processions, music, and colour.' },
          { name: 'Handicraft Markets', description: 'Local artisans showcase traditional weaving, pottery, and jewellery.' },
          { name: 'Music Scene', description: 'From classical to fusion, experience the rich musical traditions of the region.' },
        ],
      };
    }
  }
}

