import { Injectable, ForbiddenException, NotFoundException, InternalServerErrorException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiService {
  private genAI: GoogleGenerativeAI;

  constructor(private readonly prisma: PrismaService, private configService: ConfigService) {
    this.genAI = new GoogleGenerativeAI(
      this.configService.get<string>('GEMINI_API_KEY') || 'dummy_key_for_build',
    );
  }

  // ─── DB Cache helpers ─────────────────────────────────────────────
  private destKey(destination: string) {
    return destination.toLowerCase().trim();
  }

  private async getDbCache(destination: string) {
    return this.prisma.aiDestinationCache.findUnique({
      where: { destination: this.destKey(destination) },
    });
  }

  private async upsertDbCache(destination: string, field: 'overview' | 'highlights', data: any) {
    const key = this.destKey(destination);
    await this.prisma.aiDestinationCache.upsert({
      where: { destination: key },
      create: { destination: key, [field]: data },
      update: { [field]: data },
    });
  }

  // ─── Gemini model helper ──────────────────────────────────────────
  private getModel() {
    return this.genAI.getGenerativeModel({
      model: 'gemini-2.0-flash',
      generationConfig: { responseMimeType: 'application/json' },
    });
  }

  private async getTripDetails(tripId: string, userId: string) {
    const trip = await this.prisma.trip.findUnique({
      where: { id: tripId },
      include: { members: true },
    });
    if (!trip) throw new NotFoundException('Trip not found');
    const isMember = trip.members.some((m) => m.userId === userId);
    if (!isMember) throw new ForbiddenException('Access denied');
    return trip;
  }

  // ─── Itinerary ────────────────────────────────────────────────────
  async generateItinerary(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Plan an itinerary for a trip to ${trip.destination}.
      Start Date: ${trip.startDate.toDateString()}
      End Date: ${trip.endDate.toDateString()}
      Budget: ${trip.budget ? '$' + trip.budget : 'Flexible'}
      Return a JSON array of days. Each day should have a 'dayNumber' and an 'activities' array.
      Each activity should have 'title', 'description', 'locationName', and 'costEstimate'.
      Keep it realistic and concise. Output ONLY pure JSON.
    `;

    try {
      const completion = await this.getModel().generateContent(prompt);
      const result = completion.response.text();
      if (!result) throw new InternalServerErrorException('No content generated by AI');
      const parsedData = JSON.parse(result);
      return { success: true, generatedItinerary: parsedData.days || [] };
    } catch (error: any) {
      console.error('Gemini Error (Itinerary):', error?.status, error?.message);
      if (error?.status === 429 || error?.message?.includes('429')) {
        return { success: true, generatedItinerary: this.mockItinerary(trip) };
      }
      throw new InternalServerErrorException('Failed to generate itinerary. Please try again.');
    }
  }

  // ─── Packing List ─────────────────────────────────────────────────
  async generatePackingList(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Create a comprehensive packing list for a trip to ${trip.destination} between ${trip.startDate.toDateString()} and ${trip.endDate.toDateString()}.
      Output ONLY a JSON object with categories as keys and arrays of strings as values.
    `;

    try {
      const completion = await this.getModel().generateContent(prompt);
      return JSON.parse(completion.response.text() || '{}');
    } catch (error: any) {
      if (error?.status === 429 || error?.message?.includes('429')) return this.mockPackingList();
      throw new InternalServerErrorException('Failed to generate packing list.');
    }
  }

  // ─── Travel Tips ──────────────────────────────────────────────────
  async generateTravelTips(tripId: string, userId: string) {
    const trip = await this.getTripDetails(tripId, userId);

    const prompt = `
      Provide 5 crucial travel tips, cultural norms, and safety warnings for visiting ${trip.destination}.
      Output ONLY a JSON array of strings.
    `;

    try {
      const completion = await this.getModel().generateContent(prompt);
      return { tips: completion.response.text() };
    } catch (error: any) {
      if (error?.status === 429 || error?.message?.includes('429')) return { tips: JSON.stringify(this.mockTips(trip.destination)) };
      throw new InternalServerErrorException('Failed to generate travel tips.');
    }
  }

  // ─── Destination Overview (DB-cached) ────────────────────────────
  async generateDestinationOverview(destination: string) {
    // 1. Check DB cache first
    const cached = await this.getDbCache(destination);
    if (cached?.overview) {
      console.log(`[AI DB Cache HIT] overview: ${destination}`);
      return cached.overview;
    }

    const prompt = `
      Act as an expert travel guide. Provide a detailed, highly accurate travel overview of "${destination}" as a JSON object with these keys:
      "description" (3-4 paragraph overview), "history" (2-3 paragraph summary),
      "topAttractions" (array of 5 attractions with brief 1-sentence descriptions),
      "weather" (typical climate throughout the year), "bestTimeToVisit",
      "language", "currency", "timezone", "transport".
      Output ONLY pure JSON.
    `;

    try {
      const completion = await this.getModel().generateContent(prompt);
      const parsed = JSON.parse(completion.response.text() || '{}');
      // 2. Save to DB so this destination never calls Gemini again
      await this.upsertDbCache(destination, 'overview', parsed);
      console.log(`[AI DB Cache SET] overview: ${destination}`);
      return parsed;
    } catch (error: any) {
      console.error('Gemini Error (Overview):', error?.status);
      return this.mockOverview(destination);
    }
  }

  // ─── Destination Highlights (DB-cached) ──────────────────────────
  async generateDestinationHighlights(destination: string) {
    // 1. Check DB cache first
    const cached = await this.getDbCache(destination);
    if (cached?.highlights) {
      console.log(`[AI DB Cache HIT] highlights: ${destination}`);
      return cached.highlights;
    }

    const prompt = `
      Act as a travel expert. For "${destination}", provide a JSON object with:
      "attractions": array of 6 top tourist places (each: { "name", "description" }),
      "thingsToDo": array of 6 top activities (each: { "name", "description" }),
      "foods": array of 6 must-try dishes (each: { "name", "description" }),
      "culture": array of 4 cultural highlights (each: { "name", "description" }).
      Make it specific and factually accurate. Output ONLY valid JSON.
    `;

    try {
      const completion = await this.getModel().generateContent(prompt);
      const result = JSON.parse(completion.response.text() || '{}');
      // 2. Save to DB
      await this.upsertDbCache(destination, 'highlights', result);
      console.log(`[AI DB Cache SET] highlights: ${destination}`);
      return result;
    } catch (error: any) {
      console.error('Gemini Error (Highlights):', error?.status);
      return this.mockHighlights(destination);
    }
  }

  // ─── Mock fallbacks ───────────────────────────────────────────────
  private mockItinerary(trip: any) {
    return [
      { day: 1, date: trip.startDate.toISOString().split('T')[0], activities: [
        { time: '10:00 AM', description: `Arrive in ${trip.destination} and check in.`, costEstimate: 0 },
        { time: '01:00 PM', description: 'Enjoy a local welcome lunch.', costEstimate: 25 },
        { time: '07:00 PM', description: 'Welcome dinner with regional specialties.', costEstimate: 40 },
      ]},
      { day: 2, date: trip.endDate.toISOString().split('T')[0], activities: [
        { time: '09:00 AM', description: 'Visit famous landmarks and historical sites.', costEstimate: 30 },
        { time: '08:00 PM', description: 'Farewell dinner.', costEstimate: 50 },
      ]},
    ];
  }

  private mockPackingList() {
    return {
      Clothing: ['T-shirts', 'Comfortable walking shoes', 'Jacket', 'Underwear and socks'],
      Toiletries: ['Toothbrush', 'Deodorant', 'Sunscreen', 'Travel shampoo'],
      Electronics: ['Smartphone', 'Power bank', 'Travel adapter', 'Headphones'],
      Documents: ['Passport/ID', 'Travel insurance', 'Booking confirmations', 'Emergency cash'],
    };
  }

  private mockTips(destination: string) {
    return [
      `Always carry ₹500–1000 in local cash for small vendors in ${destination}.`,
      'Learn a few basic phrases in the local language.',
      'Download offline maps on your phone.',
      'Keep emergency contact numbers on a physical card.',
      'Respect local cultural dress codes at religious sites.',
    ];
  }

  private mockOverview(destination: string) {
    return {
      description: `${destination} is a vibrant destination celebrated for its unique culture and rich heritage.`,
      history: `${destination} has a fascinating history spanning centuries.`,
      topAttractions: ['Historic Old Town', 'Natural Landmarks', 'Local Museums', 'Street Food Trail', 'Sacred Temples'],
      bestTimeToVisit: 'October to March for pleasant weather.',
      weather: 'Hot summers, monsoon June–Sep, pleasant winters 15–25°C.',
      language: 'Hindi, English, and local languages',
      currency: 'INR (₹)',
      timezone: 'UTC+05:30 (IST)',
      transport: 'Autos, Buses, Cab (Ola/Uber), Metro',
    };
  }

  private mockHighlights(destination: string) {
    return {
      attractions: [
        { name: 'Old Town Quarter', description: `Historic heart of ${destination}.` },
        { name: 'Central Park', description: 'A serene green escape.' },
        { name: 'Art & History Museum', description: 'Rich cultural collections.' },
        { name: 'Waterfront Promenade', description: 'Scenic waterfront walk.' },
        { name: 'Royal Palace/Fort', description: 'Iconic royal landmark.' },
        { name: 'Night Market', description: 'Street food and local crafts.' },
      ],
      thingsToDo: [
        { name: 'Street Food Tour', description: 'Explore local flavours.' },
        { name: 'Sunrise Viewpoint', description: 'Breathtaking dawn views.' },
        { name: 'Cooking Class', description: 'Learn traditional recipes.' },
        { name: 'Cycling Tour', description: 'Discover hidden gems.' },
        { name: 'Temple Visit', description: 'Experience spiritual ambiance.' },
        { name: 'Day Trip', description: 'Scenic rural escape.' },
      ],
      foods: [
        { name: 'Local Biryani', description: 'Aromatic spiced rice.' },
        { name: 'Street Chaat', description: 'Crispy tangy snacks.' },
        { name: 'Masala Dosa', description: 'Crispy crepe with filling.' },
        { name: 'Filter Coffee', description: 'Traditional strong brew.' },
        { name: 'Seafood Platter', description: 'Fresh catch of the day.' },
        { name: 'Local Sweets', description: 'Traditional confections.' },
      ],
      culture: [
        { name: 'Classical Dance', description: 'Regional dance performances.' },
        { name: 'Temple Festivals', description: 'Vibrant religious celebrations.' },
        { name: 'Handicraft Markets', description: 'Local artisan showcases.' },
        { name: 'Music Scene', description: 'Classical to fusion music.' },
      ],
    };
  }
}
